spring:
  application:
    name: "MosaicBot"
  liquibase:
    enabled: false
  datasource:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://db/app"
    username: "agent"
    password: "agent"
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: "update"

app:
  telegram-token: "7043737603:AAHuUK8KyQQ6QX-hs_7TT5ESd4e4sF3zCZA"
  code-generator-url: "app"
  admin-login: "admin@admin.com"
  admin-password: "admin"